DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    auth_id VARCHAR(50) NOT NULL,
    y1 VARCHAR(50) NOT NULL,
    y2 VARCHAR(50) NOT NULL,
    r1 VARCHAR(50) NOT NULL,
    r2 VARCHAR(50) NOT NULL,
    c VARCHAR(50) NOT NULL
);